Authorization
Team06-Ya-Practicum/game pull request #4
Opened 2022-04-07 21:03 UTC by aberezin97

2022-04-08 11:33 UTC, Jarith requested changes
Давай разделим логику отображения и запросов данных. Сейчас проблема в том, что реакт компоненты напрямую ходят в axios. Такое сложно поддерживать, потому что при изменении инфраструктурной логики (к примеру завтра поняли, что нам нужен `fetch`, а не `axios`) придется менять кучу мест в отображении.
Удобно все связанное с запросами перенести в отдельную папку и достать наружу функции вроде `getUserInfo()` и их использовать в остальном коде

2022-04-08 11:33 UTC, jarith commented on package.json
> +        "url": "git+https://github.com/Jarith/react-redux-starter.git"
Давай пропишем url этого репозитория, а не шаблона. В `bugs` и `homepage` тоже

2022-04-08 11:33 UTC, jarith commented on package.json
> +    "name": "react-redux-starter",
Тут какое-то автоформатирование применилось?

2022-04-08 11:33 UTC, jarith commented on src/components/PrivateRoute/index.tsx
> +export const PrivateRoute = (props: IPrivateRouteProps) => {
Можно разворачивать сразу в аргументе

```suggestion
export const PrivateRoute = ({component}: IPrivateRouteProps) => {
```

2022-04-08 11:33 UTC, jarith commented on src/components/PrivateRoute/index.tsx
> +    }
1. Для неавторизованного пользователя сначала отрендерится компонент и потом произойдет редирект на форму входа
2. Стейт никогда не переключается в `true`обратно. Значит, после первого неавторизованного захода `PrivateRoute` всегда будет редирректить на `/signin`

2022-04-08 11:33 UTC, jarith commented on src/components/PrivateRoute/index.tsx
> +        .catch(() => setIsAuthorized(false));
В реакте для любых сайд-эффектов внутри компонента нужно использовать хук `useEffect`

2022-04-08 11:33 UTC, Jarith commented on src/components/PublicRoute/index.tsx
> +export const PublicRoute = (props: IPublicRouteProps) => {
Для паблик роутов в принципе нет смысла проверять авторизацию - на то они и паблик

2022-04-08 11:33 UTC, Jarith commented on src/index.tsx
> +                    path="/signin"
Имена роутов повторяются во многих местах приложения. Каждый раз писать их руками неудобно, а еще неудобнее будет менять в случае чего.
Лучше всего вынести в константу. Что-то типа такого:

```typescript
const ROUTES = {
    SIGN_IN: 'signin',
    SIGH_UP: 'signup',
    ...
};
```

2022-04-08 11:33 UTC, Jarith commented on src/pages/SignIn/index.tsx
> +    });
Конфиг в `useFormik` никак не связан с кодом компонента, его лучше вынести отдельно

2022-04-08 11:33 UTC, Jarith commented on src/pages/SignIn/index.tsx
> +                        </Form.Group>
Этот блок легко вынести в отдельный компонент и переиспользовать для полей формы.
Иначе даже в форме из двух полей получается очень много одинакового кода, который тяжело читать и поддерживать

2022-04-08 11:33 UTC, Jarith commented on src/validators.ts
> +    );
Валидации вводимых данных на фронте должны соответствовать ограничениям бэкенда. В сваггере вроде есть эта инфа. Если нет, то предлагаю подергать ручки и выяснить самому 🙂

2022-04-08 11:33 UTC, Jarith commented on webpack.config.js
> +        proxy: {
Это не будет работать в проде, потому что там не запускается devServer вебпака. Адрес нужно указывать в конфиге axios в `baseUrl`

2022-04-08 19:29 UTC, aberezin97 commented on package.json
> +    "name": "react-redux-starter",
Похоже

2022-04-09 00:47 UTC, aberezin97 commented on src/validators.ts
> +    );
login — от 3 до 20 символов, латиница, может содержать цифры, но не состоять из них, без пробелов, без спецсимволов (допустимы дефис и нижнее подчёркивание).

Так вроде все верно :)

2022-04-09 18:06 UTC, aberezin97 commented on src/pages/SignIn/index.tsx
> +    });
В onSubmit используется хук, как тогда лучше написать?

2022-04-09 19:26 UTC, aberezin97 commented on src/components/PublicRoute/index.tsx
> +export const PublicRoute = (props: IPublicRouteProps) => {
Тогда авторизированный пользователь сможет повторно войти или зарегистрироваться

2022-04-11 21:49 UTC, Jarith commented on src/validators.ts
> +    );
Ну вот я через сваггер смог зарегать пользователя и с пустым логином, и состоящим только из цифр, и с пробелами.
Получается, что фронт искусственно ограничивает пользователя в выборе логина без какой-либо причины, тем самым ухудшая его опыт взаимодействия с приложением

2022-04-11 22:18 UTC, Jarith commented on src/components/Input/index.tsx
> +            onChange={formik.handleChange}
В базовых компонентах лучше иметь минимум зависимостей. Тогда их станет проще переиспользовать в разных частях приложения.
Тут лучше убрать зависимость от `formik` и все значения принимать через пропсы

```suggestion
            onChange={onChange}
```

2022-04-11 22:18 UTC, Jarith commented on src/components/Input/index.tsx
> +        ) : null}
Опять же, для разных полей может быть разная логика отображения ошиибки. В базовом компоненте все сценарии предусмотреть не получится, поэтому лучше просто принимать флаг с текущим состоянием компонента

```typescript
interface IInputProps {
    status: 'normal' | 'error';
    errorMessage?: string;
    ...
}

export const Input = ({status, errorMessage, ...}) => {
    ....
    {status === 'error' ? (
        <Form.Control.Feedback type="invalid">
           {errorMessage}
        </Form.Control.Feedback>
     ) : null}

2022-04-11 22:18 UTC, Jarith commented on src/components/PrivateRoute/index.tsx
> +        getUserInfo().then(response => {
Забыл подсветить еще один момент. Сейчас при отправке формы дожидаемся ответа от сервера, при этом никак не говорим пользователю о происходящем. При долгом ответе возникнет ощущение, что интерфейс просто завис. При любых асинхронных действиях обычно показывают индикатор загрузки.

Это можно сделать в отдельном PR

2022-04-12 17:55 UTC, jarith approved these changes

2022-04-13 20:39 UTC, Jarith approved these changes

2022-04-13 23:07 UTC, merged